# Generated by Django 6.1 on 2026-08-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leaves_trendcategory_attendancerecord_graceperiod_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attendancelead',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='hrstaff',
            managers=[
            ],
        ),
    ]
