# Generated by Django 6.1 on 2026-08-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancelead_managers_alter_hrstaff_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='excelfile',
            name='file',
            field=models.FileField(default='', upload_to='excel_uploads/'),
            preserve_default=False,
        ),
    ]
