# Generated by Django 6.1 on 2026-09-13 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_excelfile_file_name_excelfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendancelead',
            options={'verbose_name': 'Attendance Lead', 'verbose_name_plural': 'Attendance Leads'},
        ),
        migrations.RenameField(
            model_name='uploadconflict',
            old_name='source_file',
            new_name='new_source_file',
        ),
        migrations.RemoveField(
            model_name='uploadconflict',
            name='description',
        ),
        migrations.RemoveField(
            model_name='uploadconflict',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='TEMP001', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadconflict',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadconflict',
            name='new_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadconflict',
            name='new_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadconflict',
            name='new_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uploadconflict',
            name='old_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadconflict',
            name='old_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadconflict',
            name='old_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='uploadconflict',
            name='old_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='uploadconflict',
            name='resolution',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.department'),
        ),
    ]
