# Generated by Django 6.1 on 2026-09-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_department_alter_attendancelead_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyreportentry',
            name='is_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlyreportentry',
            name='mission_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreportentry',
            name='service_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreportentry',
            name='total_hours_with_leave',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together={('department', 'month', 'year')},
        ),
    ]
