# Generated by Django 6.1 on 2026-09-14 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_monthlyreport_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlytrendreport',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlytrendreport',
            name='output_type',
            field=models.CharField(choices=[('table', 'Table'), ('chart', 'Chart')], default='table', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='yearlytrendreport',
            name='categories',
        ),
        migrations.AddField(
            model_name='yearlytrendreport',
            name='categories',
            field=models.ManyToManyField(blank=True, to='attendance.leaves'),
        ),
    ]
