# Generated by Django 6.1 on 2026-09-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_yearlytrendreport_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlytrendreport',
            name='display_number',
            field=models.IntegerField(default=1),
        ),
    ]
