# Generated by Django 6.1 on 2026-09-17 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_yearlytrendreport_display_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='gap_resolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancerecord'),
        ),
    ]
