# Generated by Django 6.1 on 2026-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancerecord_gap_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='period_type',
            field=models.CharField(choices=[('month', 'Per Month'), ('year', 'Per Year')], default='year', max_length=10),
        ),
    ]
