# Generated by Django 6.1 on 2026-09-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_leaves_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreportentry',
            name='total_late_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
