# Generated by Django 6.1 on 2026-09-19 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_monthlyreportentry_total_late_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graceperiod',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department', unique=True),
        ),
    ]
