# Generated by Django 6.1 on 2026-09-19 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_graceperiod_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='graceperiod',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='graceperiod',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='graceperiod',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
